[package]
name = "mkxp-window"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "mkxp-window"
path = "src/main.rs"

[dependencies]
mkxp-graphics = { path = "../mkxp-graphics" }
winit = "0.30"
wgpu = "24"
pollster = "0.4"
muda = "0.15"
crossbeam-channel = "0.5"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
