[package]
name = "mkxp-window"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "mkxp-window"
path = "src/main.rs"

[dependencies]
mkxp-log = { path = "../mkxp-log" }
mkxp-graphics = { path = "../mkxp-graphics" }
winit = "0.30"
wgpu = "24"
pollster = "0.4"
muda = "0.15"
crossbeam-channel = "0.5"
tracing = "0.1"
